spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/oauth2/callback/google
            scope:
              - profile
              - email
          naver:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/oauth2/callback/naver
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope:
              - nickname
              - email
              - profile_image
            client-name: Naver
          kakao:
            client-id:
            client-secret:
            redirect-uri: http://localhost:8080/oauth2/callback/kakao
            client-authentication-method: post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname,
              - profile_image,
              - account_email
            client-name: Kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#app
app:
  auth:
    token-secret:
    access-token-expiration-msec: 3600000
    refresh-token-expiration-msec: 1209600000
  cors:
    allowed-origins: http://localhost:3000, http://localhost:8080
  oauth2:
    authorized-redirect-uris: http://localhost:3000/oauth2/redirect, myandroidapp://oauth2/redirect, myiosapp://oauth2/redirect