#DB 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://home-for-paws-mysql.cy8lwbfvwfd1.ap-northeast-2.rds.amazonaws.com:3306/home-for-paws
    username: admin
    password: pawpaw73

#JPA 설정
  jpa:
    database-platform:
    hibernate:
      ddl-auto: validate

#배포 할 떄는 open-in-view false 설정
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
